#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="$ROOT_DIR/.venv"
ENV_FILE="$ROOT_DIR/.env.dashboard"

echo "================================================"
echo "OpenCode Ad Dashboard - WSL Setup"
echo "================================================"

# ============================================================
# [0/6] Verify Linux environment (no Windows paths)
# ============================================================
if [[ "$PATH" == *"/mnt/c"* ]]; then
  echo "WARNING: Windows paths detected in PATH."
  echo "This will cause OpenCode CLI to install Windows binaries."
  echo "Fix: Remove Windows paths or run: export PATH=\$(echo \"\$PATH\" | tr ':' '\n' | grep -v '/mnt/c' | tr '\n' ':')"
  echo ""
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not found. Install Python 3.10+ first."
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "npm not found. Install Node.js LTS first."
  exit 1
fi

# Verify Linux npm (not Windows)
NPM_PATH="$(which npm)"
if [[ "$NPM_PATH" == *"/mnt/c"* ]]; then
  echo "ERROR: Using Windows npm ($NPM_PATH)."
  echo "Install Linux Node.js: curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt install -y nodejs"
  exit 1
fi
echo "Using Linux npm: $NPM_PATH"

# ============================================================
# [1/6] Creating Python virtualenv
# ============================================================
if [[ ! -d "$VENV_DIR" ]]; then
  echo "[1/6] Creating Python virtualenv"
  python3 -m venv "$VENV_DIR"
else
  echo "[1/6] Reusing existing Python virtualenv"
fi

# ============================================================
# [2/6] Installing Python dependencies + Playwright
# ============================================================
echo "[2/6] Installing Python dependencies"
"$VENV_DIR/bin/pip" install --upgrade pip >/dev/null
"$VENV_DIR/bin/pip" install -r "$ROOT_DIR/requirements-dashboard.txt"

echo "[2/6] Installing Playwright (for image generation)"
"$VENV_DIR/bin/pip" install playwright >/dev/null
if ! "$VENV_DIR/bin/python" -m playwright install --with-deps chromium 2>/dev/null; then
  echo "Playwright browser install skipped (may require sudo for system deps)."
  echo "Run manually: sudo $VENV_DIR/bin/python -m playwright install --with-deps chromium"
fi

# ============================================================
# [3/6] Checking OpenCode CLI
# ============================================================
echo "[3/6] Checking OpenCode CLI"
if command -v opencode >/dev/null 2>&1; then
  OC_PATH="$(which opencode)"
  OC_VERSION="$(opencode --version 2>/dev/null || echo 'unknown')"
  echo "OpenCode already installed: $OC_VERSION ($OC_PATH)"
  
  # Verify it's a Linux binary
  if file "$OC_PATH" 2>/dev/null | grep -q "ELF"; then
    echo "  -> Linux binary confirmed."
  elif [[ "$OC_PATH" == *"/mnt/c"* ]] || file "$OC_PATH" 2>/dev/null | grep -q "PE32"; then
    echo "  -> WARNING: Windows binary detected. Reinstall with: sudo npm install -g opencode-ai"
  fi
else
  echo "Installing OpenCode CLI (opencode-ai)..."
  sudo npm install -g opencode-ai
  opencode --version || true
fi

# ============================================================
# [4/6] Preparing storage folders
# ============================================================
echo "[4/6] Preparing storage folders"
mkdir -p \
  "$ROOT_DIR/dashboard_storage/pids" \
  "$ROOT_DIR/dashboard_storage/logs" \
  "$ROOT_DIR/dashboard_storage/runs" \
  "$ROOT_DIR/input/docs" \
  "$ROOT_DIR/input/images" \
  "$ROOT_DIR/runtime/opencode_queue" \
  "$ROOT_DIR/runtime/gemini_selected_prompts" \
  "$ROOT_DIR/runtime/chatgpt_selected_prompts" \
  "$ROOT_DIR/runtime/conversion_916_prompts" \
  "$ROOT_DIR/runtime/generation_logs" \
  "$ROOT_DIR/output" \
  "$ROOT_DIR/generated_images"

# ============================================================
# [5/6] Writing .env.dashboard (if missing)
# ============================================================
echo "[5/6] Checking .env.dashboard"
if [[ ! -f "$ENV_FILE" ]]; then
  PASSWORD="$(python3 - <<'PY'
import secrets
import string
alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+?"
print("".join(secrets.choice(alphabet) for _ in range(20)))
PY
)"
  cat > "$ENV_FILE" <<EOF
# OpenCode Ad Dashboard - Auto-generated by setup_wsl.sh
# Do not share this file. Add it to .gitignore.
OPENCODE_SERVER_PASSWORD=$PASSWORD
OPENCODE_API_URL=http://127.0.0.1:4090
EOF
  echo "Created $ENV_FILE"
else
  echo "Keeping existing $ENV_FILE"
fi

# ============================================================
# [6/6] Clear stale OpenCode state (prevents Session not found)
# ============================================================
echo "[6/6] Checking OpenCode local state"
OC_STATE_DIR="${HOME}/.local/share/opencode"
if [[ -d "$OC_STATE_DIR" ]]; then
  echo "Existing OpenCode state found. Clearing to prevent session errors..."
  rm -rf "$OC_STATE_DIR"
  echo "Cleared $OC_STATE_DIR"
else
  echo "No stale state found."
fi

# ============================================================
# Summary
# ============================================================
echo
echo "================================================"
echo "Setup complete!"
echo "================================================"
echo
echo "Next steps:"
echo "  1) Configure AI provider: opencode providers login"
echo "  2) Verify models: opencode models"
echo "  3) Start dashboard: bash scripts/start_dashboard_stack.sh"
echo "  4) Open browser: http://127.0.0.1:8787"
echo
echo "To stop: bash scripts/stop_dashboard_stack.sh"
