#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="$ROOT_DIR/.venv"
ENV_FILE="$ROOT_DIR/.env.dashboard"

echo "================================================"
echo "OpenCode Ad Dashboard - WSL Setup"
echo "================================================"

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not found. Install Python 3.10+ first."
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "npm not found. Install Node.js LTS first."
  exit 1
fi

if [[ ! -d "$VENV_DIR" ]]; then
  echo "[1/5] Creating Python virtualenv"
  python3 -m venv "$VENV_DIR"
else
  echo "[1/5] Reusing existing Python virtualenv"
fi

echo "[2/5] Installing Python dependencies"
"$VENV_DIR/bin/pip" install --upgrade pip >/dev/null
"$VENV_DIR/bin/pip" install -r "$ROOT_DIR/requirements-dashboard.txt"

echo "[3/5] Installing OpenCode CLI (opencode-ai)"
npm install -g opencode-ai
opencode --version || true

echo "[4/5] Preparing storage folders"
mkdir -p \
  "$ROOT_DIR/dashboard_storage/pids" \
  "$ROOT_DIR/dashboard_storage/logs" \
  "$ROOT_DIR/dashboard_storage/runs" \
  "$ROOT_DIR/input/docs" \
  "$ROOT_DIR/input/images" \
  "$ROOT_DIR/runtime/opencode_queue" \
  "$ROOT_DIR/runtime/gemini_selected_prompts" \
  "$ROOT_DIR/runtime/chatgpt_selected_prompts" \
  "$ROOT_DIR/runtime/conversion_916_prompts" \
  "$ROOT_DIR/runtime/generation_logs" \
  "$ROOT_DIR/output" \
  "$ROOT_DIR/generated_images"

echo "[5/5] Writing .env.dashboard (if missing)"
if [[ ! -f "$ENV_FILE" ]]; then
  PASSWORD="$(python3 - <<'PY'
import secrets
import string
alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+?"
print("".join(secrets.choice(alphabet) for _ in range(20)))
PY
)"
  cat > "$ENV_FILE" <<EOF
# OpenCode Ad Dashboard - Auto-generated by setup_wsl.sh
# Do not share this file. Add it to .gitignore.
OPENCODE_SERVER_PASSWORD=$PASSWORD
OPENCODE_API_URL=http://127.0.0.1:4090
EOF
  echo "Created $ENV_FILE"
else
  echo "Keeping existing $ENV_FILE"
fi

echo
echo "Setup complete."
echo "Next:"
echo "  1) opencode providers login"
echo "  2) opencode models"
echo "  3) bash scripts/start_dashboard_stack.sh"
